services:
  - type: web
    name: diasure-app
    runtime: python
    region: oregon  # or frankfurt, singapore, etc.
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        sync: production # Set the value securely in the Render Dashboard
